name: Build Push and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Log in to Docker Hub
       uses: docker/login-action@v3
       with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASS }}

     
     - name: Build and push to dockerhub
       uses: docker/build-push-action@v5
       with:
           push: true
           tags: chafiqq/lab-project:latest


          
    

          
